// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export * from '../exports';
export * from '/root/devops-md/node_modules/.store/dumi@2.1.17/node_modules/dumi/dist/client/theme-api/index.js';
